/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VditorEditor: typeof import('./src/components/VditorEditor.vue')['default']
    VditorSimple: typeof import('./src/components/VditorSimple.vue')['default']
    VditorTest: typeof import('./src/components/VditorTest.vue')['default']
  }
}
